include:
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v6.yml'

image: ubuntu:bionic

variables:
  JULIA_CUDA_VERBOSE: 'true'
  NVIDIA_VISIBLE_DEVICES: 'all'
  NVIDIA_DRIVER_CAPABILITIES: 'compute,utility'


# Julia versions

julia:1.0:
  extends:
    - .julia:1.0
    - .test
  tags:
    - nvidia

julia:1.1:
  extends:
    - .julia:1.1
    - .test
  tags:
    - nvidia

# the "primary" target, where we require thorough tests
# (this requires a recent GPU)
julia:1.2:
  image: juliagpu/cuda:10.1-cudnn7-cutensor1-devel-ubuntu18.04
  extends:
    - .julia:1.2
    - .test
  tags:
    - nvidia
    - sm_75
  variables:
    CI_THOROUGH: 'true'

julia:1.3:
  extends:
    - .julia:1.3
    - .test
  tags:
    - nvidia

julia:nightly:
  extends:
    - .julia:nightly
    - .test
  tags:
    - nvidia
  allow_failure: true


# CUDA versions

# NOTE: we support those CUDA versions for which the latest cuDNN is available
#       https://developer.nvidia.com/rdp/cudnn-archive

cuda:10.1:
  extends:
    - .julia:1.2
    - .test
  variables:
    JULIA_CUDA_VERSION: '10.1'
  tags:
    - nvidia

cuda:10.0:
  extends:
    - .julia:1.2
    - .test
  variables:
    JULIA_CUDA_VERSION: '10.0'
  tags:
    - nvidia

cuda:9.2:
  extends:
    - .julia:1.2
    - .test
  variables:
    JULIA_CUDA_VERSION: '9.2'
  tags:
    - nvidia

# NOTE: CUDA 9.0 is broken

cuda:local:
  extends:
    - .julia:1.2
    - .test
  image: nvidia/cuda:10.1-devel-ubuntu18.04
  variables:
    JULIA_CUDA_USE_BINARYBUILDER: 'false'
  tags:
    - nvidia

cuda:none:
  extends:
    - .julia:1.2
    - .test
  variables:
    JULIA_CUDA_USE_BINARYBUILDER: 'false'
  script:
    - julia -e 'using InteractiveUtils;
                versioninfo()'
    - julia --project -e 'using Pkg;
                          Pkg.instantiate();
                          Pkg.build();
                          Pkg.API.precompile();'
    - julia --project -e 'using CuArrays'


# hardware platforms

platform:arm64:
  image: nvcr.io/nvidia/l4t-base:r32.2.1
  extends:
    - .julia:1.2
    - .test
  tags:
    - nvidia-arm64


# special tests

pool:none:
  extends:
    - .julia:1.2
    - .test
  tags:
    - nvidia
  variables:
    CUARRAYS_MEMORY_POOL: 'none'

pool:simple:
  extends:
    - .julia:1.2
    - .test
  tags:
    - nvidia
  variables:
    CUARRAYS_MEMORY_POOL: 'simple'

pool:split:
  extends:
    - .julia:1.2
    - .test
  tags:
    - nvidia
  variables:
    CUARRAYS_MEMORY_POOL: 'split'


# reverse tests

# NOTE: reverse testing is tricky because of Manifests. we instantiate both, give priority
#       to this package's Manifest, and manually run tests outside of the test environment.
#       that means we have to manually install Flux' test dependencies though.

flux:
  extends: .julia:1.2
  tags:
    - nvidia
  script:
    - export FLUX=".julia/dev/Flux"
    - julia -e 'using Pkg;
                Pkg.develop("Flux");'
    - julia --project -e 'using Pkg;
                          Pkg.instantiate();
                          Pkg.build();'
    - julia --project=$FLUX -e 'using Pkg;
                                Pkg.instantiate();
                                Pkg.build();
                                Pkg.add(["Documenter"]);'
    - JULIA_LOAD_PATH=".:$FLUX::" julia $FLUX/test/runtests.jl
  allow_failure: true


# other tasks

coverage:
  extends:
    - .julia:1.2
    - .coverage

documentation:
  extends:
    - .julia:1.2
    - .documentation
  tags:
    - nvidia

pages:
  stage: deploy
  script:
    - mv docs/build public
  artifacts:
    paths:
    - public
  only:
    - master
